### PR TITLE
feat(copilot): load GitHub token from environment

### PR DESCRIPTION
**Pull request by lingjie00**
The copilot module now first tries to load the GitHub token from the environment variable 'GITHUB_TOKEN'. If the variable is not set, it falls back to loading the token from the file.

### CODE REVIEW

**Comment by gptlang** [comment]
Can we name it something other than GITHUB_TOKEN? That's a common environment variable name used by other programs.

**Comment by lingjie00** [comment]
> Can we name it something other than GITHUB_TOKEN? That's a common environment variable name used by other programs.

Initially I was thinking to re-use the GITHUB_TOKEN already in the environment. Do you think we should let user to maybe choose the variable in config while setting the default as GITHUB_TOKEN?

**Comment by deathbeam** [comment]
It definitely should not be configurable, we should just follow whatever github does. Which means we should also check for the CODESPACE env variable like the copilot.vim does.

**Review by deathbeam — APPROVED** [review]

**Review by acheong08 — APPROVED** [review]
For reference:

```js
                async getGitHubToken(t) {
                        if (process.env.CODESPACES === "true" && process.env.GITHUB_TOKEN)
                                return { token: process.env.GITHUB_TOKEN };
```
in https://github.com/github/copilot.vim/blob/release/dist/agent.js

Edit: Oops wrong account

**Comment by jellydn** [comment]
@all-contributors add @lingjie00 for code.

**Pull request merged**
