### PR TITLE
fix: avoid nil value happen at posting obj

### PR DESCRIPTION
**Pull request by weykon**
```
    {
        "CopilotC-Nvim/CopilotChat.nvim",
        branch = "canary",
        dependencies = {
            { "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
            { "nvim-lua/plenary.nvim" },  -- for curl, log wrapper
        },
        opts = {
            debug = true, -- Enable debugging
            -- See Configuration section for rest
        },
        config = function()
            require("CopilotChat").setup({ debug = true })
            vim.keymap.set("v", "<leader>ai", "<cmd>CopilotChatToggle<CR>")
        end
    },
```
I was using lunarvim to load it into use, and the configuration is as above. 
Every time I enter prompt after selection and then press enter, there will be errors.
I looked it up and tried to solve it like this. 
I am not familiar with lua, so I am not sure if it is reasonable to modify it like this, but it has no errors.
Please give me some advice on how to discover the problems and modify them.
Thanks !

### CODE REVIEW

**Comment by deathbeam** [comment]
I dont have this issue, is it possible that your plenary.nvim dependency is outdated?

**Comment by weykon** [comment]
It may be this problem. I saw that the commit of plenary.nvim is 2023, which is relatively old, but when I reinstalled it, he still installed that version. I still don't know how to set them. 
I had update Lvim and Plugins with update command

**Comment by deathbeam** [comment]
yea, the plugin requires very recent plenary version to function properly. I dont use lazy.nvim so not sure what could be the problem and why is it not updating but maybe @jellydn knows?

**Comment by jellydn** [comment]
You could use `commit=f7adfc4b3f4f91aab6caebf42b3682945fbc35be` with lazy.nvim to pin to the latest commit @weykon

**Comment by weykon** [comment]
I switched to f7adfc4 you said, the function can be used normally. thank you both!

**Pull request closed without merging**
