### PR TITLE
Add migration guide to README.md

### PR DESCRIPTION
**Pull request by deathbeam**
Did not updated rest of the README yet but at least for migration this should be enough.

### CODE REVIEW

**Review by jellydn — COMMENTED** [review]
Thanks, @deathbeam Could you add a working example with the canary branch? Then it would be super useful if someone want to take atry. What do you think?

**Comment by deathbeam** [comment]
> Thanks, @deathbeam Could you add a working example with the canary branch? Then it would be super useful if someone want to take atry. What do you think?

By working example you mean like full config with something like lazy.nvim? As I dont use plugin managers so im not confident in making the working example actually work :d

**Comment by jellydn** [comment]
If so @deathbeam Could you share how to setup it on your end? I will translate to the plugin managers :)

**Comment by deathbeam** [comment]
> If so @deathbeam Could you share how to setup it on your end? I will translate to the plugin managers :)

Sure, I have submodule for
- [copilot.vim](https://github.com/github/copilot.vim)
- [plenary.nvim](https://github.com/nvim-lua/plenary.nvim)
- [CopilotChat.nvim(https://github.com/CopilotC-Nvim/CopilotChat.nvim) on branch `canary`

And then this is how I configure it for myself atm (from linked line to end of file):
https://github.com/deathbeam/dotfiles/blob/master/nvim/.config/nvim/lua/config/copilot.lua#L14

**Pull request merged**
