### PR TITLE
Minor restructure for pynvim 0.4.3 backwards compatibility 

### PR DESCRIPTION
**Pull request by errnoh**
I was wondering why just cloning the repo to `rplugin/python3` and running `:UpdateRemotePlugins` didn't work and spent some time looking into it. Turns out that it should, but some issues in the structure prevent that. To fix that I modified the rplugin and related imports to work similarly to the [example pynvim module](https://github.com/neovim/pynvim/tree/master/test/fixtures/module_plugin/rplugin/python3/mymodule).

pros:
- No longer requires manual steps, just clone it to the correct location as expected.
- Fixes things like https://github.com/CopilotC-Nvim/CopilotChat.nvim/issues/16 (relative imports now correctly identify that it's a package)
- Easier to add the package to nixpkgs etc

cons:
- All local imports done with * imports, making it a bit harder to know which file the functions are coming from. No idea why `from .XXX import *` works but `from .XXX import Y, Z` doesn't.

### CODE REVIEW

**Comment by jellydn** [comment]
Thanks @errnoh for your work.

> why just cloning the repo to rplugin/python3 and running :UpdateRemotePlugins didn't work

I tried the manual install on the 1st version from @gptlang and it works for me. 

> Turns out that it should, but some issues in the structure prevent that

Could you elaborate on this point? What is your neovim setup, python version?

**Comment by errnoh** [comment]
@jellydn hmm, interestingly enough I think the main issue seems to be that I had two pynvim versions installed and CopilotChat used one for it's heatlhcheck and vim actually used the other one for executing commands.

What this PR actually seems to do is at least provide backwards compatibility with pynvim 0.4.3.

---

With the repo cloned to `~/.config/nvim/pack/vendor/start`, no additional commands other than `require('CopilotChat').setup{}`:

`main` branch
```
- Python version: 3.11.6
- pynvim version: 0.4.3
```
```
> :UpdateRemotePlugins
Encountered ModuleNotFoundError loading plugin at /home/errnoh/.con
fig/nvim/pack/vendor/start/CopilotChat.nvim/rplugin/python3/copilot
-plugin.py: No module named 'handlers'                             
Traceback (most recent call last):                                 
  File "/nix/store/a5y5ik9hwz1n8jf5y6a8hfwmd5r84w9l-python3-3.11.6-
env/lib/python3.11/site-packages/pynvim/plugin/host.py", line 165, 
in _load                                                           
    module = imp.load_module(name, file, pathname, descr)          
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^          
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/
lib/python3.11/imp.py", line 235, in load_module                   
    return load_source(name, filename, file)                       
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                       
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/
lib/python3.11/imp.py", line 172, in load_source                   
    module = _load(spec)                                           
             ^^^^^^^^^^^                                           
  File "<frozen importlib._bootstrap>", line 721, in _load         
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
                                                                   
ModuleNotFoundError: No module named 'handlers'                    
                                                                   
Encountered ModuleNotFoundError loading plugin at /home/errnoh/.con
fig/nvim/pack/vendor/start/CopilotChat.nvim/rplugin/python3/copilot
.py: No module named 'prompts'                                     
Traceback (most recent call last):                                 
  File "/nix/store/a5y5ik9hwz1n8jf5y6a8hfwmd5r84w9l-python3-3.11.6-
env/lib/python3.11/site-packages/pynvim/plugin/host.py", line 165, 
in _load                                                           
    module = imp.load_module(name, file, pathname, descr)          
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^          
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/
lib/python3.11/imp.py", line 235, in load_module                   
    return load_source(name, filename, file)                       
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                       
  File "/nix/store/rac8pxbi1vapwrlqzbrkycbyg521djzw-python3-3.11.6/
lib/python3.11/imp.py", line 172, in load_source                   
    module = _load(spec)                                           
             ^^^^^^^^^^^                                           
  File "<frozen importlib._bootstrap>", line 721, in _load         
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
                                                                   
ModuleNotFoundError: No module named 'prompts'                     
                                                                   
remote/host: python3 host registered plugins ['mymodule']          
remote/host: generated rplugin manifest: /home/errnoh/.local/share/
nvim/rplugin.vim                                
```
(mymodule is not related)

`errnoh/dev` branch
```
- Python version: 3.11.6
- pynvim version: 0.4.3

Copilotchat.nvim health check:
- WARNING python 3 is required
```
```
> :UpdateRemotePlugins
remote/host: python3 host registered plugins ['CopilotChat', 'mymodule']                              
remote/host: generated rplugin manifest: /home/errnoh/.local/share/nvim/rplugin.vim
```
```
:CopilotChatExplain

### User
Explain how it works.

### Copilot

<expected response here>
```

With the 0.4.3 removed and only using 0.5.0:

```
- Python version: 3.11.6
- pynvim version: 0.5.0

Copilotchat.nvim health check:
- OK Python version 3.11 is supported
- OK pynvim version 0.5.0 is supported
```

Both `main` and `errnoh/dev` work fine.

**Comment by errnoh** [comment]
Though the health check not working in this setup should probably be fixed as well. Is it using python found from `g:python3_host_prog` or just checking for any python binary? Neovim in NixOS is often using wrapped python that's named `nvim-python3` so maybe that's why it's reporting that it's finding the other binary instead?

**Comment by jellydn** [comment]
Great. Thanks @errnoh. I've just changed this PR to `canary` branch instead of `main`. 

Let's see if @gptlang and @ziontee113 have any comments/thoughts on this PR. 

IMO, I could merge this to canary and test on my side as well.

**Comment by errnoh** [comment]
Added one more commit to ensure that the correct python binary is being used and that it reports >=0.4.3 as valid versions.

**Comment by gptlang** [comment]
In what versions does relative imports not work? I really don't like `import *`s

Could adding `__init__.py`s to every directory help it identify the fact that it's a package?

**Comment by errnoh** [comment]
Took a look at this with fresh pair of eyes and figured out a simple way to get best of both worlds. Imports are now fixed in the latest commit and are 1:1 with the original code but just added package declaration at the start of the import.
-

**Comment by jellydn** [comment]
Thanks @errnoh Could you fix the conflict? 

image

**Comment by errnoh** [comment]
> Thanks @errnoh Could you fix the conflict?
> image

There you go :+1:  @jellydn

**Review by jellydn — APPROVED** [review]
LGTM!

**Pull request merged**
